# Generated by Django 3.1.2 on 2020-11-26 05:54

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img', upload_to=image.models.Image.path_and_rename_I)),
                ('weight', models.ImageField(default='wgt', upload_to=image.models.Image.path_and_rename_W)),
            ],
        ),
    ]
